//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bicycle_rent
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Bicycle state.
    /// </summary>
    // *** Start programmer edit section *** (BicycleState CustomAttributes)

    // *** End programmer edit section *** (BicycleState CustomAttributes)
    public enum BicycleState
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (BicycleState.Исправен CustomAttributes)

        // *** End programmer edit section *** (BicycleState.Исправен CustomAttributes)
        Исправен,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (BicycleState.Неисправен CustomAttributes)

        // *** End programmer edit section *** (BicycleState.Неисправен CustomAttributes)
        Неисправен,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (BicycleState.Украден CustomAttributes)

        // *** End programmer edit section *** (BicycleState.Украден CustomAttributes)
        Украден,
    }
}
