//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bicycle_rent
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Bicycle type.
    /// </summary>
    // *** Start programmer edit section *** (BicycleType CustomAttributes)

    // *** End programmer edit section *** (BicycleType CustomAttributes)
    public enum BicycleType
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (BicycleType.Горный CustomAttributes)

        // *** End programmer edit section *** (BicycleType.Горный CustomAttributes)
        Горный,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (BicycleType.Шоссейный CustomAttributes)

        // *** End programmer edit section *** (BicycleType.Шоссейный CustomAttributes)
        Шоссейный,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (BicycleType.Детский CustomAttributes)

        // *** End programmer edit section *** (BicycleType.Детский CustomAttributes)
        Детский,
    }
}
