//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bicycle_rent
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Bicycle.
    /// </summary>
    // *** Start programmer edit section *** (Bicycle CustomAttributes)

    // *** End programmer edit section *** (Bicycle CustomAttributes)
    [AutoAltered()]
    [Caption("Велосипед")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("BicycleE", new string[] {
            "Number",
            "Model as \'Модель\'",
            "Description as \'Описание\'",
            "CostPerMinute as \'Стоимость/мин\'",
            "Type as \'Тип\'",
            "State as \'Состояние\'",
            "CurPoint as \'Пункт\'"})]
    [MasterViewDefineAttribute("BicycleE", "CurPoint", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Address")]
    [View("BicycleL", new string[] {
            "Number",
            "Model as \'Модель\'",
            "Description as \'Описание\'",
            "CostPerMinute as \'Стоимость/мин\'",
            "Type as \'Тип\'",
            "State as \'Состояние\'",
            "IsFree as \'Свободен\'"})]
    public class Bicycle : ICSSoft.STORMNET.DataObject
    {
        
        private int fNumber;
        
        private string fModel;
        
        private string fDescription;
        
        private double fCostPerMinute;
        
        private Bicycle_rent.BicycleType fType;
        
        private Bicycle_rent.BicycleState fState;
        
        private bool fIsFree;
        
        private Bicycle_rent.Point fCurPoint;
        
        // *** Start programmer edit section *** (Bicycle CustomMembers)

        // *** End programmer edit section *** (Bicycle CustomMembers)

        
        /// <summary>
        /// Number.
        /// </summary>
        // *** Start programmer edit section *** (Bicycle.Number CustomAttributes)

        // *** End programmer edit section *** (Bicycle.Number CustomAttributes)
        [NotNull()]
        public virtual int Number
        {
            get
            {
                // *** Start programmer edit section *** (Bicycle.Number Get start)

                // *** End programmer edit section *** (Bicycle.Number Get start)
                int result = this.fNumber;
                // *** Start programmer edit section *** (Bicycle.Number Get end)

                // *** End programmer edit section *** (Bicycle.Number Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Bicycle.Number Set start)

                // *** End programmer edit section *** (Bicycle.Number Set start)
                this.fNumber = value;
                // *** Start programmer edit section *** (Bicycle.Number Set end)

                // *** End programmer edit section *** (Bicycle.Number Set end)
            }
        }
        
        /// <summary>
        /// Model.
        /// </summary>
        // *** Start programmer edit section *** (Bicycle.Model CustomAttributes)

        // *** End programmer edit section *** (Bicycle.Model CustomAttributes)
        [StrLen(50)]
        [NotNull()]
        public virtual string Model
        {
            get
            {
                // *** Start programmer edit section *** (Bicycle.Model Get start)

                // *** End programmer edit section *** (Bicycle.Model Get start)
                string result = this.fModel;
                // *** Start programmer edit section *** (Bicycle.Model Get end)

                // *** End programmer edit section *** (Bicycle.Model Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Bicycle.Model Set start)

                // *** End programmer edit section *** (Bicycle.Model Set start)
                this.fModel = value;
                // *** Start programmer edit section *** (Bicycle.Model Set end)

                // *** End programmer edit section *** (Bicycle.Model Set end)
            }
        }
        
        /// <summary>
        /// Description.
        /// </summary>
        // *** Start programmer edit section *** (Bicycle.Description CustomAttributes)

        // *** End programmer edit section *** (Bicycle.Description CustomAttributes)
        public virtual string Description
        {
            get
            {
                // *** Start programmer edit section *** (Bicycle.Description Get start)

                // *** End programmer edit section *** (Bicycle.Description Get start)
                string result = this.fDescription;
                // *** Start programmer edit section *** (Bicycle.Description Get end)

                // *** End programmer edit section *** (Bicycle.Description Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Bicycle.Description Set start)

                // *** End programmer edit section *** (Bicycle.Description Set start)
                this.fDescription = value;
                // *** Start programmer edit section *** (Bicycle.Description Set end)

                // *** End programmer edit section *** (Bicycle.Description Set end)
            }
        }
        
        /// <summary>
        /// CostPerMinute.
        /// </summary>
        // *** Start programmer edit section *** (Bicycle.CostPerMinute CustomAttributes)

        // *** End programmer edit section *** (Bicycle.CostPerMinute CustomAttributes)
        [NotNull()]
        public virtual double CostPerMinute
        {
            get
            {
                // *** Start programmer edit section *** (Bicycle.CostPerMinute Get start)

                // *** End programmer edit section *** (Bicycle.CostPerMinute Get start)
                double result = this.fCostPerMinute;
                // *** Start programmer edit section *** (Bicycle.CostPerMinute Get end)

                // *** End programmer edit section *** (Bicycle.CostPerMinute Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Bicycle.CostPerMinute Set start)

                // *** End programmer edit section *** (Bicycle.CostPerMinute Set start)
                this.fCostPerMinute = value;
                // *** Start programmer edit section *** (Bicycle.CostPerMinute Set end)

                // *** End programmer edit section *** (Bicycle.CostPerMinute Set end)
            }
        }
        
        /// <summary>
        /// Type.
        /// </summary>
        // *** Start programmer edit section *** (Bicycle.Type CustomAttributes)

        // *** End programmer edit section *** (Bicycle.Type CustomAttributes)
        [NotNull()]
        public virtual Bicycle_rent.BicycleType Type
        {
            get
            {
                // *** Start programmer edit section *** (Bicycle.Type Get start)

                // *** End programmer edit section *** (Bicycle.Type Get start)
                Bicycle_rent.BicycleType result = this.fType;
                // *** Start programmer edit section *** (Bicycle.Type Get end)

                // *** End programmer edit section *** (Bicycle.Type Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Bicycle.Type Set start)

                // *** End programmer edit section *** (Bicycle.Type Set start)
                this.fType = value;
                // *** Start programmer edit section *** (Bicycle.Type Set end)

                // *** End programmer edit section *** (Bicycle.Type Set end)
            }
        }
        
        /// <summary>
        /// State.
        /// </summary>
        // *** Start programmer edit section *** (Bicycle.State CustomAttributes)

        // *** End programmer edit section *** (Bicycle.State CustomAttributes)
        [NotNull()]
        public virtual Bicycle_rent.BicycleState State
        {
            get
            {
                // *** Start programmer edit section *** (Bicycle.State Get start)

                // *** End programmer edit section *** (Bicycle.State Get start)
                Bicycle_rent.BicycleState result = this.fState;
                // *** Start programmer edit section *** (Bicycle.State Get end)

                // *** End programmer edit section *** (Bicycle.State Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Bicycle.State Set start)

                // *** End programmer edit section *** (Bicycle.State Set start)
                this.fState = value;
                // *** Start programmer edit section *** (Bicycle.State Set end)

                // *** End programmer edit section *** (Bicycle.State Set end)
            }
        }
        
        /// <summary>
        /// IsFree.
        /// </summary>
        // *** Start programmer edit section *** (Bicycle.IsFree CustomAttributes)

        // *** End programmer edit section *** (Bicycle.IsFree CustomAttributes)
        public virtual bool IsFree
        {
            get
            {
                // *** Start programmer edit section *** (Bicycle.IsFree Get start)

                // *** End programmer edit section *** (Bicycle.IsFree Get start)
                bool result = this.fIsFree;
                // *** Start programmer edit section *** (Bicycle.IsFree Get end)

                // *** End programmer edit section *** (Bicycle.IsFree Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Bicycle.IsFree Set start)

                // *** End programmer edit section *** (Bicycle.IsFree Set start)
                this.fIsFree = value;
                // *** Start programmer edit section *** (Bicycle.IsFree Set end)

                // *** End programmer edit section *** (Bicycle.IsFree Set end)
            }
        }
        
        /// <summary>
        /// Bicycle.
        /// </summary>
        // *** Start programmer edit section *** (Bicycle.CurPoint CustomAttributes)

        // *** End programmer edit section *** (Bicycle.CurPoint CustomAttributes)
        [PropertyStorage(new string[] {
                "CurPoint"})]
        public virtual Bicycle_rent.Point CurPoint
        {
            get
            {
                // *** Start programmer edit section *** (Bicycle.CurPoint Get start)

                // *** End programmer edit section *** (Bicycle.CurPoint Get start)
                Bicycle_rent.Point result = this.fCurPoint;
                // *** Start programmer edit section *** (Bicycle.CurPoint Get end)

                // *** End programmer edit section *** (Bicycle.CurPoint Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Bicycle.CurPoint Set start)

                // *** End programmer edit section *** (Bicycle.CurPoint Set start)
                this.fCurPoint = value;
                // *** Start programmer edit section *** (Bicycle.CurPoint Set end)

                // *** End programmer edit section *** (Bicycle.CurPoint Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "BicycleE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View BicycleE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("BicycleE", typeof(Bicycle_rent.Bicycle));
                }
            }
            
            /// <summary>
            /// "BicycleL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View BicycleL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("BicycleL", typeof(Bicycle_rent.Bicycle));
                }
            }
        }
    }
}
