//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bicycle_rent
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Car.
    /// </summary>
    // *** Start programmer edit section *** (Car CustomAttributes)

    // *** End programmer edit section *** (Car CustomAttributes)
    [AutoAltered()]
    [Caption("Автомобиль")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("CarE", new string[] {
            "Model as \'Модель\'",
            "Number as \'Гос. номер\'"})]
    [View("CarL", new string[] {
            "Model as \'Модель\'",
            "Number as \'Гос. номер\'"})]
    public class Car : ICSSoft.STORMNET.DataObject
    {
        
        private string fModel;
        
        private string fNumber;
        
        // *** Start programmer edit section *** (Car CustomMembers)

        // *** End programmer edit section *** (Car CustomMembers)

        
        /// <summary>
        /// Model.
        /// </summary>
        // *** Start programmer edit section *** (Car.Model CustomAttributes)

        // *** End programmer edit section *** (Car.Model CustomAttributes)
        [StrLen(50)]
        [NotNull()]
        public virtual string Model
        {
            get
            {
                // *** Start programmer edit section *** (Car.Model Get start)

                // *** End programmer edit section *** (Car.Model Get start)
                string result = this.fModel;
                // *** Start programmer edit section *** (Car.Model Get end)

                // *** End programmer edit section *** (Car.Model Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Car.Model Set start)

                // *** End programmer edit section *** (Car.Model Set start)
                this.fModel = value;
                // *** Start programmer edit section *** (Car.Model Set end)

                // *** End programmer edit section *** (Car.Model Set end)
            }
        }
        
        /// <summary>
        /// Number.
        /// </summary>
        // *** Start programmer edit section *** (Car.Number CustomAttributes)

        // *** End programmer edit section *** (Car.Number CustomAttributes)
        [StrLen(10)]
        [NotNull()]
        public virtual string Number
        {
            get
            {
                // *** Start programmer edit section *** (Car.Number Get start)

                // *** End programmer edit section *** (Car.Number Get start)
                string result = this.fNumber;
                // *** Start programmer edit section *** (Car.Number Get end)

                // *** End programmer edit section *** (Car.Number Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Car.Number Set start)

                // *** End programmer edit section *** (Car.Number Set start)
                this.fNumber = value;
                // *** Start programmer edit section *** (Car.Number Set end)

                // *** End programmer edit section *** (Car.Number Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "CarE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CarE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CarE", typeof(Bicycle_rent.Car));
                }
            }
            
            /// <summary>
            /// "CarL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CarL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CarL", typeof(Bicycle_rent.Car));
                }
            }
        }
    }
}
