//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bicycle_rent
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Client.
    /// </summary>
    // *** Start programmer edit section *** (Client CustomAttributes)

    // *** End programmer edit section *** (Client CustomAttributes)
    [AutoAltered()]
    [Caption("Клиент")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ClientE", new string[] {
            "DocData as \'Документ\'",
            "FullName as \'ФИО\'",
            "Gender as \'Пол\'"})]
    [View("ClientL", new string[] {
            "DocData as \'Документ\'",
            "FullName as \'ФИО\'",
            "Gender as \'Пол\'"})]
    public class Client : Bicycle_rent.Human
    {
        
        private string fDocData;
        
        // *** Start programmer edit section *** (Client CustomMembers)

        // *** End programmer edit section *** (Client CustomMembers)

        
        /// <summary>
        /// DocData.
        /// </summary>
        // *** Start programmer edit section *** (Client.DocData CustomAttributes)

        // *** End programmer edit section *** (Client.DocData CustomAttributes)
        [StrLen(150)]
        [NotNull()]
        public virtual string DocData
        {
            get
            {
                // *** Start programmer edit section *** (Client.DocData Get start)

                // *** End programmer edit section *** (Client.DocData Get start)
                string result = this.fDocData;
                // *** Start programmer edit section *** (Client.DocData Get end)

                // *** End programmer edit section *** (Client.DocData Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Client.DocData Set start)

                // *** End programmer edit section *** (Client.DocData Set start)
                this.fDocData = value;
                // *** Start programmer edit section *** (Client.DocData Set end)

                // *** End programmer edit section *** (Client.DocData Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ClientE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ClientE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ClientE", typeof(Bicycle_rent.Client));
                }
            }
            
            /// <summary>
            /// "ClientL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ClientL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ClientL", typeof(Bicycle_rent.Client));
                }
            }
        }
    }
}
