//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bicycle_rent
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Employee.
    /// </summary>
    // *** Start programmer edit section *** (Employee CustomAttributes)

    // *** End programmer edit section *** (Employee CustomAttributes)
    [AutoAltered()]
    [Caption("Сотрудник")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("EmployeeE", new string[] {
            "FullName as \'ФИО\'",
            "Position as \'Должность\'",
            "Gender as \'Пол\'"})]
    [View("EmployeeL", new string[] {
            "FullName as \'ФИО\'",
            "Position as \'Должность\'",
            "Gender as \'Пол\'"})]
    public class Employee : Bicycle_rent.Human
    {
        
        private Bicycle_rent.Positions fPosition;
        
        // *** Start programmer edit section *** (Employee CustomMembers)

        // *** End programmer edit section *** (Employee CustomMembers)

        
        /// <summary>
        /// Position.
        /// </summary>
        // *** Start programmer edit section *** (Employee.Position CustomAttributes)

        // *** End programmer edit section *** (Employee.Position CustomAttributes)
        [NotNull()]
        public virtual Bicycle_rent.Positions Position
        {
            get
            {
                // *** Start programmer edit section *** (Employee.Position Get start)

                // *** End programmer edit section *** (Employee.Position Get start)
                Bicycle_rent.Positions result = this.fPosition;
                // *** Start programmer edit section *** (Employee.Position Get end)

                // *** End programmer edit section *** (Employee.Position Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Employee.Position Set start)

                // *** End programmer edit section *** (Employee.Position Set start)
                this.fPosition = value;
                // *** Start programmer edit section *** (Employee.Position Set end)

                // *** End programmer edit section *** (Employee.Position Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "EmployeeE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View EmployeeE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("EmployeeE", typeof(Bicycle_rent.Employee));
                }
            }
            
            /// <summary>
            /// "EmployeeL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View EmployeeL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("EmployeeL", typeof(Bicycle_rent.Employee));
                }
            }
        }
    }
}
