//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bicycle_rent
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Genders.
    /// </summary>
    // *** Start programmer edit section *** (Genders CustomAttributes)

    // *** End programmer edit section *** (Genders CustomAttributes)
    public enum Genders
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (Genders.М CustomAttributes)

        // *** End programmer edit section *** (Genders.М CustomAttributes)
        М,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (Genders.Ж CustomAttributes)

        // *** End programmer edit section *** (Genders.Ж CustomAttributes)
        Ж,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (Genders.Неопределено CustomAttributes)

        // *** End programmer edit section *** (Genders.Неопределено CustomAttributes)
        Неопределено,
    }
}
