//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bicycle_rent
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Positions.
    /// </summary>
    // *** Start programmer edit section *** (Positions CustomAttributes)

    // *** End programmer edit section *** (Positions CustomAttributes)
    public enum Positions
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (Positions.Директор CustomAttributes)

        // *** End programmer edit section *** (Positions.Директор CustomAttributes)
        Директор,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (Positions.Менеджер CustomAttributes)

        // *** End programmer edit section *** (Positions.Менеджер CustomAttributes)
        Менеджер,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (Positions.Водитель CustomAttributes)

        // *** End programmer edit section *** (Positions.Водитель CustomAttributes)
        Водитель,
    }
}
