//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bicycle_rent
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Session state.
    /// </summary>
    // *** Start programmer edit section *** (SessionState CustomAttributes)

    // *** End programmer edit section *** (SessionState CustomAttributes)
    public enum SessionState
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (SessionState.Открыта CustomAttributes)

        // *** End programmer edit section *** (SessionState.Открыта CustomAttributes)
        Открыта,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (SessionState.Закрыта CustomAttributes)

        // *** End programmer edit section *** (SessionState.Закрыта CustomAttributes)
        Закрыта,
    }
}
