//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bicycle_rent
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Transport session string.
    /// </summary>
    // *** Start programmer edit section *** (TransportSessionString CustomAttributes)

    // *** End programmer edit section *** (TransportSessionString CustomAttributes)
    [AutoAltered()]
    [Caption("Transport session string")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("TransportSessionStringE", new string[] {
            "Bicycle as \'Велосипед\'"})]
    [MasterViewDefineAttribute("TransportSessionStringE", "Bicycle", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Model")]
    [View("TransportSessionStringL", new string[] {
            "Bicycle.Number",
            "Bicycle.Model",
            "Bicycle.State",
            "Bicycle"}, Hidden=new string[] {
            "Bicycle"})]
    public class TransportSessionString : ICSSoft.STORMNET.DataObject
    {
        
        private Bicycle_rent.Bicycle fBicycle;
        
        private Bicycle_rent.TransportSession fTransportSession;
        
        // *** Start programmer edit section *** (TransportSessionString CustomMembers)

        // *** End programmer edit section *** (TransportSessionString CustomMembers)

        
        /// <summary>
        /// Transport session string.
        /// </summary>
        // *** Start programmer edit section *** (TransportSessionString.Bicycle CustomAttributes)

        // *** End programmer edit section *** (TransportSessionString.Bicycle CustomAttributes)
        [PropertyStorage(new string[] {
                "Bicycle"})]
        [NotNull()]
        public virtual Bicycle_rent.Bicycle Bicycle
        {
            get
            {
                // *** Start programmer edit section *** (TransportSessionString.Bicycle Get start)

                // *** End programmer edit section *** (TransportSessionString.Bicycle Get start)
                Bicycle_rent.Bicycle result = this.fBicycle;
                // *** Start programmer edit section *** (TransportSessionString.Bicycle Get end)

                // *** End programmer edit section *** (TransportSessionString.Bicycle Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (TransportSessionString.Bicycle Set start)

                // *** End programmer edit section *** (TransportSessionString.Bicycle Set start)
                this.fBicycle = value;
                // *** Start programmer edit section *** (TransportSessionString.Bicycle Set end)

                // *** End programmer edit section *** (TransportSessionString.Bicycle Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку Bicycle_rent.TransportSession.
        /// </summary>
        // *** Start programmer edit section *** (TransportSessionString.TransportSession CustomAttributes)

        // *** End programmer edit section *** (TransportSessionString.TransportSession CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "TransportSession"})]
        public virtual Bicycle_rent.TransportSession TransportSession
        {
            get
            {
                // *** Start programmer edit section *** (TransportSessionString.TransportSession Get start)

                // *** End programmer edit section *** (TransportSessionString.TransportSession Get start)
                Bicycle_rent.TransportSession result = this.fTransportSession;
                // *** Start programmer edit section *** (TransportSessionString.TransportSession Get end)

                // *** End programmer edit section *** (TransportSessionString.TransportSession Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (TransportSessionString.TransportSession Set start)

                // *** End programmer edit section *** (TransportSessionString.TransportSession Set start)
                this.fTransportSession = value;
                // *** Start programmer edit section *** (TransportSessionString.TransportSession Set end)

                // *** End programmer edit section *** (TransportSessionString.TransportSession Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "TransportSessionStringE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View TransportSessionStringE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("TransportSessionStringE", typeof(Bicycle_rent.TransportSessionString));
                }
            }
            
            /// <summary>
            /// "TransportSessionStringL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View TransportSessionStringL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("TransportSessionStringL", typeof(Bicycle_rent.TransportSessionString));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of TransportSessionString.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfTransportSessionString CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfTransportSessionString CustomAttributes)
    public class DetailArrayOfTransportSessionString : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (Bicycle_rent.DetailArrayOfTransportSessionString members)

        // *** End programmer edit section *** (Bicycle_rent.DetailArrayOfTransportSessionString members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type TransportSessionString by index.
        /// </summary>
        /// <summary>
        /// Adds object with type TransportSessionString.
        /// </summary>
        public DetailArrayOfTransportSessionString(Bicycle_rent.TransportSession fTransportSession) : 
                base(typeof(TransportSessionString), ((ICSSoft.STORMNET.DataObject)(fTransportSession)))
        {
        }
        
        public Bicycle_rent.TransportSessionString this[int index]
        {
            get
            {
                return ((Bicycle_rent.TransportSessionString)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(Bicycle_rent.TransportSessionString dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
