//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bicycle_rent
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Transport state.
    /// </summary>
    // *** Start programmer edit section *** (TransportState CustomAttributes)

    // *** End programmer edit section *** (TransportState CustomAttributes)
    public enum TransportState
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (TransportState.Отбыл CustomAttributes)

        // *** End programmer edit section *** (TransportState.Отбыл CustomAttributes)
        Отбыл,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (TransportState.Прибыл CustomAttributes)

        // *** End programmer edit section *** (TransportState.Прибыл CustomAttributes)
        Прибыл,
    }
}
