<%--flexberryautogenerated="true"--%>
<%@ Page Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="BicyclePopularity.aspx.cs" Inherits="Bicycle_rent.BicyclePopularity" Title="Untitled Page" %>

<asp:Content ID="Content1" ContentPlaceHolderID="PageTitlePlaceholder" runat="server">
    Популярность велосипедов по типам
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="AddToHeadPlaceholder" runat="server">
</asp:Content>

<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <p><asp:Label CssClass="descLbl" ID="lblMountain" runat="server" Text="" EnableViewState="False" /></p>
    <p><asp:Label CssClass="descLbl" ID="lblHighway" runat="server" Text="" EnableViewState="False" /></p>
    <p><asp:Label CssClass="descLbl" ID="lblChildren" runat="server" Text="" EnableViewState="False" /></p>
</asp:Content>

<asp:Content ID="Content4" ContentPlaceHolderID="ContentPlaceHolder0" runat="server">
</asp:Content>
