/*flexberryautogenerated="false"*/
using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;

namespace Bicycle_rent
{
    public partial class BicyclePopularity : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            lblChildren.Text = $"Детский: {Statistics.GetRentsCount(BicycleType.Детский).ToString()}";
            lblHighway.Text = $"Шоссейный {Statistics.GetRentsCount(BicycleType.Шоссейный).ToString()}";
            lblMountain.Text = $"Горный: {Statistics.GetRentsCount(BicycleType.Горный).ToString()}";
        }
    }
}
