/*flexberryautogenerated="true"*/
using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;

namespace Bicycle_rent
{
    public partial class BrokenBicycles : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
        }

        protected void btnCalcResult_Click(object sender, EventArgs e)
        {
            if (ctrlFromDate.Value != null && ctrlUntilDate.Value != null && ctrlFromDate.Value < ctrlUntilDate.Value)
            {
                var data = Statistics.RuinedBicycles(ctrlFromDate.Value, ctrlUntilDate.Value);
                ctrlDamagedBicyclesLabel.Text = $"Испорчено велосипедов: {data.Item1.ToString()}";
                ctrlStolenBicyclesLabel.Text = $"Украдено велосипедов: {data.Item2.ToString()}";
            }
            else { ICSSoft.STORMNET.Web.AjaxControls.WebMessageBox.Show("Данные не заполнены или некорректны"); }
        }
    }
}
