<%--flexberryautogenerated="false"--%>
<%@ Page Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="PointsProfit.aspx.cs" Inherits="Bicycle_rent.PointsProfit" Title="Untitled Page" %>
<asp:Content ID="Content1" ContentPlaceHolderID="PageTitlePlaceholder" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="AddToHeadPlaceholder" runat="server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="descTxt">
        <asp:Label CssClass="descLbl" ID="ctrlFromDateLabel" runat="server" Text="От" EnableViewState="False" />
        <ac:DatePicker ID="ctrlFromDate" runat="server"/>
        <asp:Label CssClass="descLbl" ID="ctrlUntilDateLabel" runat="server" Text="До" EnableViewState="False" />
        <ac:DatePicker ID="ctrlUntilDate" runat="server"/>
        <asp:Label CssClass="descLbl" ID="ctrlPointLabel" runat="server" Text="Точка" EnableViewState="False" />
        <ac:MasterEditorAjaxLookUp ID="ctrlPoint" CssClass="descTxt" ShowInThickBox="True" Autocomplete="true" runat="server" />
        <asp:Button runat="server" ID="btnCalcResult" Text="Рассчитать" OnClick="btnCalcResult_Click" />

        <asp:Label CssClass="descLbl" ID="ctrlProfitLabel" runat="server" Text="" EnableViewState="False" />
    </div>
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="ContentPlaceHolder0" runat="server">
</asp:Content>
