<%--flexberryautogenerated="true"--%>
<%@ Page Language="C#" MasterPageFile="~/Site1.Master"  AutoEventWireup="true" CodeBehind="BicycleE.aspx.cs" Inherits="Bicycle_rent.BicycleE" %>
<%@ Import namespace="NewPlatform.Flexberry.Web.Page" %>
<%-- Autogenerated section start [Register] --%>
<%-- Autogenerated section end [Register] --%>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="<%= Constants.FormCssClass %> <%= Constants.EditFormCssClass %>">
        <h2 class="<%= Constants.FormHeaderCssClass %> <%= Constants.EditFormHeaderCssClass %>">Велосипеды</h2>
        <div class="<%= Constants.FormToolbarCssClass %> <%= Constants.EditFormToolbarCssClass %> <%= Constants.StickyCssClass %>">
            <asp:ImageButton ID="SaveBtn" runat="server" SkinID="SaveBtn" OnClick="SaveBtn_Click" AlternateText="<%$ Resources: Resource, Save %>" ValidationGroup="savedoc" />
            <asp:ImageButton ID="SaveAndCloseBtn" runat="server" SkinID="SaveAndCloseBtn" OnClick="SaveAndCloseBtn_Click" AlternateText="<%$ Resources: Resource, Save_Close %>" ValidationGroup="savedoc" />
            <asp:ImageButton ID="CancelBtn" runat="server" SkinID="CancelBtn" OnClick="CancelBtn_Click" AlternateText="<%$ Resources: Resource, Cancel %>" />
        </div>
        <div class="<%= Constants.FormControlsCssClass %> <%= Constants.EditFormControlsCssClass %>">
            <%-- Autogenerated section start [Controls] --%>
<!-- autogenerated start -->
<div>
	<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlNumberLabel" runat="server" Text="Number" EnableViewState="False">
</asp:Label>
<ac:AlphaNumericTextBox CssClass="descTxt" ID="ctrlNumber" Type="Numeric" runat="server">
</ac:AlphaNumericTextBox>

<asp:RequiredFieldValidator ID="ctrlNumberValidator" runat="server" ControlToValidate="ctrlNumber"
ErrorMessage="Не указано: Number" EnableClientScript="true" ValidationGroup="savedoc">*</asp:RequiredFieldValidator>

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlModelLabel" runat="server" Text="Модель" EnableViewState="False">
</asp:Label>
<asp:TextBox CssClass="descTxt" ID="ctrlModel" runat="server">
</asp:TextBox>

<asp:RequiredFieldValidator ID="ctrlModelValidator" runat="server" ControlToValidate="ctrlModel"
ErrorMessage="Не указано: Model" EnableClientScript="true" ValidationGroup="savedoc">*</asp:RequiredFieldValidator>

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlDescriptionLabel" runat="server" Text="Описание" EnableViewState="False">
</asp:Label>
<asp:TextBox CssClass="descTxt" ID="ctrlDescription" runat="server">
</asp:TextBox>

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlCostPerMinuteLabel" runat="server" Text="Стоимость/мин" EnableViewState="False">
</asp:Label>
<ac:DecimalTextBox CssClass="descTxt" ID="ctrlCostPerMinute" runat="server">
</ac:DecimalTextBox>

<asp:RequiredFieldValidator ID="ctrlCostPerMinuteValidator" runat="server" ControlToValidate="ctrlCostPerMinute"
ErrorMessage="Не указано: CostPerMinute" EnableClientScript="true" ValidationGroup="savedoc">*</asp:RequiredFieldValidator>

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlTypeLabel" runat="server" Text="Тип" EnableViewState="False">
</asp:Label>
<asp:DropDownList ID="ctrlType" CssClass="descTxt" runat="server">
	<asp:ListItem>Горный</asp:ListItem>
<asp:ListItem>Шоссейный</asp:ListItem>
<asp:ListItem>Детский</asp:ListItem>

</asp:DropDownList>
<asp:RequiredFieldValidator ID="ctrlTypeValidator" runat="server" ControlToValidate="ctrlType"
ErrorMessage="Не указано: Type" EnableClientScript="true" ValidationGroup="savedoc">*</asp:RequiredFieldValidator>

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlStateLabel" runat="server" Text="Состояние" EnableViewState="False">
</asp:Label>
<asp:DropDownList ID="ctrlState" CssClass="descTxt" runat="server">
	<asp:ListItem>Исправен</asp:ListItem>
<asp:ListItem>Неисправен</asp:ListItem>
<asp:ListItem>Украден</asp:ListItem>

</asp:DropDownList>
<asp:RequiredFieldValidator ID="ctrlStateValidator" runat="server" ControlToValidate="ctrlState"
ErrorMessage="Не указано: State" EnableClientScript="true" ValidationGroup="savedoc">*</asp:RequiredFieldValidator>

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlCurPointLabel" runat="server" Text="Пункт" EnableViewState="False">
</asp:Label>
<ac:MasterEditorAjaxLookUp ID="ctrlCurPoint" CssClass="descTxt" runat="server" ShowInThickBox="True" Autocomplete="true" />

</div>

</div>
<!-- autogenerated end -->
            <%-- Autogenerated section end [Controls] --%>
        </div>
    </div>
</asp:Content>
