/*flexberryautogenerated="true"*/
namespace Bicycle_rent
{
    using System;
    using ICSSoft.STORMNET.Web.Controls;

    using Resources;

    public partial class CarL : BaseListForm<Car>
    {
        /// <summary>
        /// Конструктор без параметров,
        /// инициализирует свойства, соответствующие конкретной форме.
        /// </summary>
        public CarL() : base(Car.Views.CarL)
        {
            EditPage = CarE.FormPath;
        }
                
        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/Entities/CarL.aspx"; }
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {
        }

        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {
        }
    }
}
