/*flexberryautogenerated="false"*/
namespace Bicycle_rent
{
    using System;
    using ICSSoft.STORMNET.Web.Controls;

    using Resources;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET.Business.LINQProvider;
    using System.Linq;

    public partial class FinishTransportL : BaseListForm<TransportSession>
    {
        /// <summary>
        /// Конструктор без параметров,
        /// инициализирует свойства, соответствующие конкретной форме.
        /// </summary>
        public FinishTransportL() : base(TransportSession.Views.FinishTransportL)
        {
            EditPage = FinishTransportE.FormPath;
        }
                
        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/Transport/FinishTransportL.aspx"; }
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {
            WebObjectListView1.DataObjectTypes = new[] { typeof(TransportSession) };
            WebObjectListView1.View = TransportSession.Views.FinishTransportL;
            WebObjectListView1.Operations.New = false;
            WebObjectListView1.Operations.Delete = false;

            var ds = DataServiceProvider.DataService;
            var query = ds.Query<TransportSession>(TransportSession.Views.FinishTransportL.Name)
                .Where(item => item.State.Equals(SessionState.Открыта));
            WebObjectListView1.LimitFunction = LinqToLcs.GetLcs(
                query.Expression, TransportSession.Views.FinishTransportL).LimitFunction;
        }

        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {
        }
    }
}
