/*flexberryautogenerated="false"*/

namespace Bicycle_rent
{
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Web.Controls;
    using ICSSoft.STORMNET.Web.AjaxControls;
    using ICSSoft.STORMNET.Business;

    public partial class GiveBicycleE : BaseEditForm<RentSession>
    {
        /// <summary>
        /// Конструктор формы.
        /// </summary>
        public GiveBicycleE()
            : base(RentSession.Views.GiveBicycleE)
        {
        }

        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/Rent/GiveBicycleE.aspx"; }
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {
        }

        /// <summary>
        /// Здесь лучше всего писать бизнес-логику, оперируя только объектом данных.
        /// </summary>
        protected override void PreApplyToControls()
        {
        }

        /// <summary>
        /// Здесь лучше всего изменять свойства контролов на странице,
        /// которые не обрабатываются WebBinder.
        /// </summary>
        protected override void PostApplyToControls()
        {
            Page.Validate();
        }

        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {
        }

        /// <summary>
        /// Валидация объекта для сохранения.
        /// </summary>
        /// <returns>true - продолжать сохранение, иначе - прекратить.</returns>
        protected override bool PreSaveObject()
        {
            return base.PreSaveObject();
        }

        /// <summary>
        /// Нетривиальная логика сохранения объекта.
        /// </summary>
        /// <returns>Объект данных, который сохранился.</returns>
        protected override DataObject SaveObject()
        {
            return base.SaveObject();
        }

        private void LoadObjectByPK(SQLDataService ds, DataObject obj, string pk)
        {
            obj.SetExistObjectPrimaryKey(pk);
            ds.LoadObject(obj);
        }
        protected override void SaveBtn_Click(object sender, System.Web.UI.ImageClickEventArgs e)
        {
            var ds = (SQLDataService)DataServiceProvider.DataService;

            var bicycle = new Bicycle();
            this.LoadObjectByPK(ds, bicycle, ctrlBicycle.SelectedMasterPK);

            var client = new Client();
            this.LoadObjectByPK(ds, client, ctrlClient.SelectedMasterPK);

            var emp = new Employee();
            this.LoadObjectByPK(ds, emp, ctrlEmployeeGive.SelectedMasterPK);

            var point = new Point();
            this.LoadObjectByPK(ds, point, ctrlStartPoint.SelectedMasterPK);

            var session = new RentSession
            {
                StartDate = System.DateTime.Now,
                Bicycle = bicycle,
                Client = client,
                EmployeeGive = emp,
                StartPoint = point,
                State = SessionState.Открыта,
                EndPoint = null,
                FinishDate = null,
                EmployeeTake = null
            };
            ds.UpdateObject(session);
            Response.Redirect(Request.Path);
            //ctrlBicycle.SelectedMasterPK = null;
            //ctrlClient.SelectedMasterPK = null;
            //ctrlEmployeeGive.SelectedMasterPK = null;
            //ctrlStartPoint.SelectedMasterPK = null;
        }
    }
}