<%--flexberryautogenerated="true"--%>
<%@ Page Language="C#" MasterPageFile="~/Site1.Master"  AutoEventWireup="true" CodeBehind="RentSessionE.aspx.cs" Inherits="Bicycle_rent.RentSessionE" %>
<%@ Import namespace="NewPlatform.Flexberry.Web.Page" %>
<%-- Autogenerated section start [Register] --%>
<%-- Autogenerated section end [Register] --%>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="<%= Constants.FormCssClass %> <%= Constants.EditFormCssClass %>">
        <h2 class="<%= Constants.FormHeaderCssClass %> <%= Constants.EditFormHeaderCssClass %>">Сессии проката</h2>
        <div class="<%= Constants.FormToolbarCssClass %> <%= Constants.EditFormToolbarCssClass %> <%= Constants.StickyCssClass %>">
            <asp:ImageButton ID="SaveBtn" runat="server" SkinID="SaveBtn" OnClick="SaveBtn_Click" AlternateText="<%$ Resources: Resource, Save %>" ValidationGroup="savedoc" />
            <asp:ImageButton ID="SaveAndCloseBtn" runat="server" SkinID="SaveAndCloseBtn" OnClick="SaveAndCloseBtn_Click" AlternateText="<%$ Resources: Resource, Save_Close %>" ValidationGroup="savedoc" />
            <asp:ImageButton ID="CancelBtn" runat="server" SkinID="CancelBtn" OnClick="CancelBtn_Click" AlternateText="<%$ Resources: Resource, Cancel %>" />
        </div>
        <div class="<%= Constants.FormControlsCssClass %> <%= Constants.EditFormControlsCssClass %>">
            <%-- Autogenerated section start [Controls] --%>
<!-- autogenerated start -->
<div>
	<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlStartDateLabel" runat="server" Text="Дата выдачи" EnableViewState="False">
</asp:Label>
<div class="descTxt">
    <ac:DatePicker ID="ctrlStartDate" runat="server"/>
</div>
<asp:RequiredFieldValidator ID="ctrlStartDateValidator" runat="server" ControlToValidate="ctrlStartDate"
ErrorMessage="Не указано: StartDate" EnableClientScript="true" ValidationGroup="savedoc">*</asp:RequiredFieldValidator>

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlFinishDateLabel" runat="server" Text="Дата сдачи" EnableViewState="False">
</asp:Label>
<div class="descTxt">
    <ac:DatePicker ID="ctrlFinishDate" runat="server"/>
</div>
</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlCostLabel" runat="server" Text="Стоимость" EnableViewState="False">
</asp:Label>
<ac:DecimalTextBox CssClass="descTxt" ID="ctrlCost" runat="server">
</ac:DecimalTextBox>

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlFineLabel" runat="server" Text="Штраф" EnableViewState="False">
</asp:Label>
<ac:DecimalTextBox CssClass="descTxt" ID="ctrlFine" runat="server">
</ac:DecimalTextBox>

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlSessionStateLabel" runat="server" Text="Статус" EnableViewState="False">
</asp:Label>
<asp:DropDownList ID="ctrlSessionState" CssClass="descTxt" runat="server">
	<asp:ListItem>Открыта</asp:ListItem>
<asp:ListItem>Закрыта</asp:ListItem>

</asp:DropDownList>
</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlClientLabel" runat="server" Text="Клиент" EnableViewState="False">
</asp:Label>
<ac:MasterEditorAjaxLookUp ID="ctrlClient" CssClass="descTxt" runat="server" ShowInThickBox="True" Autocomplete="true" />

<asp:RequiredFieldValidator ID="ctrlClientValidator" runat="server" ControlToValidate="ctrlClient"
ErrorMessage="Не указано: Client" EnableClientScript="true" ValidationGroup="savedoc">*</asp:RequiredFieldValidator>

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlStartPointLabel" runat="server" Text="Точка выдачи" EnableViewState="False">
</asp:Label>
<ac:MasterEditorAjaxLookUp ID="ctrlStartPoint" CssClass="descTxt" runat="server" ShowInThickBox="True" Autocomplete="true" />

<asp:RequiredFieldValidator ID="ctrlStartPointValidator" runat="server" ControlToValidate="ctrlStartPoint"
ErrorMessage="Не указано: StartPoint" EnableClientScript="true" ValidationGroup="savedoc">*</asp:RequiredFieldValidator>

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlEndPointLabel" runat="server" Text="Точка сдачи" EnableViewState="False">
</asp:Label>
<ac:MasterEditorAjaxLookUp ID="ctrlEndPoint" CssClass="descTxt" runat="server" ShowInThickBox="True" Autocomplete="true" />

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlEmployeeGiveLabel" runat="server" Text="Выдал" EnableViewState="False">
</asp:Label>
<ac:MasterEditorAjaxLookUp ID="ctrlEmployeeGive" CssClass="descTxt" runat="server" ShowInThickBox="True" Autocomplete="true" />

<asp:RequiredFieldValidator ID="ctrlEmployeeGiveValidator" runat="server" ControlToValidate="ctrlEmployeeGive"
ErrorMessage="Не указано: EmployeeGive" EnableClientScript="true" ValidationGroup="savedoc">*</asp:RequiredFieldValidator>

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlBicycleLabel" runat="server" Text="Велосипед" EnableViewState="False">
</asp:Label>
<ac:MasterEditorAjaxLookUp ID="ctrlBicycle" CssClass="descTxt" runat="server" ShowInThickBox="True" Autocomplete="true" />

<asp:RequiredFieldValidator ID="ctrlBicycleValidator" runat="server" ControlToValidate="ctrlBicycle"
ErrorMessage="Не указано: Bicycle" EnableClientScript="true" ValidationGroup="savedoc">*</asp:RequiredFieldValidator>

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlEmployeeTakeLabel" runat="server" Text="Принял" EnableViewState="False">
</asp:Label>
<ac:MasterEditorAjaxLookUp ID="ctrlEmployeeTake" CssClass="descTxt" runat="server" ShowInThickBox="True" Autocomplete="true" />

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlFinalBicycleStateLabel" runat="server" Text="Состояние велосипеда" EnableViewState="False">
</asp:Label>
<asp:DropDownList ID="ctrlFinalBicycleState" CssClass="descTxt" runat="server">
	<asp:ListItem>Исправен</asp:ListItem>
<asp:ListItem>Неисправен</asp:ListItem>
<asp:ListItem>Украден</asp:ListItem>

</asp:DropDownList>
</div>
<br/>

</div>
<!-- autogenerated end -->
            <%-- Autogenerated section end [Controls] --%>
        </div>
    </div>
</asp:Content>
