/*flexberryautogenerated="true"*/
namespace Bicycle_rent
{
    using System;
    using ICSSoft.STORMNET.Web.Controls;

    using Resources;

    public partial class RentSessionL : BaseListForm<RentSession>
    {
        /// <summary>
        /// Конструктор без параметров,
        /// инициализирует свойства, соответствующие конкретной форме.
        /// </summary>
        public RentSessionL() : base(RentSession.Views.RentSessionL)
        {
            EditPage = RentSessionE.FormPath;
        }
                
        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/Rent/RentSessionL.aspx"; }
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {
        }

        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {
        }
    }
}
