/*flexberryautogenerated="false"*/
namespace Bicycle_rent
{
    using System;
    using ICSSoft.STORMNET.Web.Controls;

    using Resources;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET.Security;
    public partial class RentSessionL : BaseListForm<RentSession>
    {
        /// <summary>
        /// Конструктор без параметров,
        /// инициализирует свойства, соответствующие конкретной форме.
        /// </summary>
        public RentSessionL() : base(RentSession.Views.RentSessionL)
        {
            EditPage = RentSessionE.FormPath;
        }
                
        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/Rent/RentSessionL.aspx"; }
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {
            WebObjectListView1.Operations.New = false;
            WebObjectListView1.Operations.NewByExampleInRow = false;

            var sm = DataServiceProvider.DataService.SecurityManager;

            if (!sm.AccessObjectCheck(typeof(RentSession), tTypeAccess.Delete, false))
            {
                WebObjectListView1.Operations.Delete = false;
            }

            if (!sm.AccessObjectCheck(typeof(RentSession), tTypeAccess.Update, false))
            {
                WebObjectListView1.Operations.EditInRow = false;
                WebObjectListView1.Operations.EditOnClickInRow = false;
            }

        }

        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {
        }
    }
}
