/*flexberryautogenerated="false"*/
namespace Bicycle_rent
{
    using System;
    using ICSSoft.STORMNET.Web.Controls;

    using Resources;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET.Business.LINQProvider;
    using System.Linq;

    public partial class TakeBicycleL : BaseListForm<RentSession>
    {
        /// <summary>
        /// Конструктор без параметров,
        /// инициализирует свойства, соответствующие конкретной форме.
        /// </summary>
        public TakeBicycleL() : base(RentSession.Views.TakeBicycleL)
        {
            EditPage = TakeBicycleE.FormPath;
        }
                
        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/Rent/TakeBicycleL.aspx"; }
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {
            WebObjectListView1.DataObjectTypes = new[] { typeof(RentSession) };
            WebObjectListView1.View = RentSession.Views.TakeBicycleL;
            WebObjectListView1.Operations.New = false;
            WebObjectListView1.Operations.Delete = false;
            
            var ds = DataServiceProvider.DataService;
            var query = ds.Query<RentSession>(RentSession.Views.TakeBicycleL.Name)
                .Where(item => item.State.Equals(SessionState.Открыта));
            WebObjectListView1.LimitFunction = LinqToLcs.GetLcs(
            query.Expression, RentSession.Views.TakeBicycleL).LimitFunction;
        }

        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {
        }
    }
}
