<%--flexberryautogenerated="true"--%>
<%@ Page Language="C#" MasterPageFile="~/Site1.Master"  AutoEventWireup="true" CodeBehind="TakeBicycleE.aspx.cs" Inherits="Bicycle_rent.TakeBicycleE" %>
<%@ Import namespace="NewPlatform.Flexberry.Web.Page" %>
<%-- Autogenerated section start [Register] --%>
<%-- Autogenerated section end [Register] --%>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="<%= Constants.FormCssClass %> <%= Constants.EditFormCssClass %>">
        <h2 class="<%= Constants.FormHeaderCssClass %> <%= Constants.EditFormHeaderCssClass %>">Забрать велосипед</h2>
        <div class="<%= Constants.FormToolbarCssClass %> <%= Constants.EditFormToolbarCssClass %> <%= Constants.StickyCssClass %>">
            <asp:ImageButton ID="SaveBtn" runat="server" SkinID="SaveBtn" OnClick="SaveBtn_Click" AlternateText="<%$ Resources: Resource, Save %>" ValidationGroup="savedoc" />
            <asp:ImageButton ID="SaveAndCloseBtn" runat="server" SkinID="SaveAndCloseBtn" OnClick="SaveAndCloseBtn_Click" AlternateText="<%$ Resources: Resource, Save_Close %>" ValidationGroup="savedoc" />
            <asp:ImageButton ID="CancelBtn" runat="server" SkinID="CancelBtn" OnClick="CancelBtn_Click" AlternateText="<%$ Resources: Resource, Cancel %>" />
        </div>
        <div class="<%= Constants.FormControlsCssClass %> <%= Constants.EditFormControlsCssClass %>">
            <%-- Autogenerated section start [Controls] --%>
<!-- autogenerated start -->
<div>
	<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlEmployeeTakeLabel" runat="server" Text="Принял" EnableViewState="False">
</asp:Label>
<ac:MasterEditorAjaxLookUp ID="ctrlEmployeeTake" CssClass="descTxt" runat="server" ShowInThickBox="True" Autocomplete="true" />

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlEndPointLabel" runat="server" Text="Точка сдачи" EnableViewState="False">
</asp:Label>
<ac:MasterEditorAjaxLookUp ID="ctrlEndPoint" CssClass="descTxt" runat="server" ShowInThickBox="True" Autocomplete="true" />

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlFineLabel" runat="server" Text="Штраф" EnableViewState="False">
</asp:Label>
<ac:DecimalTextBox CssClass="descTxt" ID="ctrlFine" runat="server">
</ac:DecimalTextBox>

</div>

<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlFinalBicycleStateLabel" runat="server" Text="Состояние велосипеда" EnableViewState="False">
</asp:Label>
<asp:DropDownList ID="ctrlFinalBicycleState" CssClass="descTxt" runat="server">
	<asp:ListItem>Исправен</asp:ListItem>
<asp:ListItem>Неисправен</asp:ListItem>
<asp:ListItem>Украден</asp:ListItem>

</asp:DropDownList>
</div>

</div>
<!-- autogenerated end -->
            <%-- Autogenerated section end [Controls] --%>
        </div>
    </div>
</asp:Content>
